services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
    - ./galleries:/app/galleries
    # - .env:/.env
    # ports:
    # - 3000:3000
    depends_on:
    - db

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/conf:/etc/caddy
